config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'search', to: 'pages#search'
  resources :articles
  # resources :posts 
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  # could restrict with a hash of only: [show, edit]
  #expose all REST-ful routes-- representational state transfer
  # basically a mapping of the HTTP verbs(get, post, put/patch, delete)
  # to CRUD actions in Rails App.
  #HTTP verbs front end requests -- CRUD actions backend responses.
  #frontend could be anything just as long as the HTTP verbs are being
  #translated into the appropriate/correct CRUD action.

end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories 
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: { minimum: 6, maximum: 100}
    validates :description, presence: true, length: { minimum: 10, maximum: 10000}


     def self.index_content
            # information = ["name", "last_name", "first_name"]
            content_hash = {}
            self.all.each do |article|
                unless article.description == nil || article.description == ""
                    article.description.split(/[\s,'-\.!]/).each do |word|
                            content_hash[word.downcase] = [] if content_hash[word.downcase].nil? 
                            content_hash[word.downcase].push(article)
                    end 
                end 
            end     
        content_hash
    end

    def self.search(search_word)
        hash = self.index_content
        hash[search_word]
    end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
                                      #[ :show, :edit, :update, :destroy ]
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]






 

  # GET /articles or /articles.json
  
  # GET /articles/1 or /articles/1.json
  def show
    @article = Article.find(params[:id])
  end
  
  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles or /articles.json
  def create

    @article = Article.new(article_params)
    @article.user = current_user

    respond_to do |format|
      if @article.save
                # this uses shortened path article_url(@article)
        format.html { redirect_to @article, notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
   

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "The article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
        @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    #white-listing so-to-speak
    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user 
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article 
      end 
    end 


end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
  <div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
           by <%= link_to article.user.username, user_path(article.user)%>
          </div>
            <% if article.categories.any?%>
              <div class="mt-2"><%= render article.categories %></div>
            <% end %>
          <div class="card-body">
            <h5 class="card-title"> <%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"> <%= truncate(article.description, length: 100) %>.</p>
              <%= link_to 'view', article_path(article), class: "btn btn-outline-success" %></a>
              <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to 'edit', edit_article_path(article), class: "btn btn-outline-info"  %></a>
                <%= link_to 'delete', article_path(article), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you REALLY sure?"} %> 
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Create ago <%= time_ago_in_words(article.created_at)%>, edited <%= time_ago_in_words(article.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/articles/_form.html.erb
  
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
        <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |form| %>
          <div class="form-group mb-2 row">
            <%= form.label :title, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
            </div>
          </div>

          <div class="form-group row">
            <%= form.label :description, class: "col-2 col-form-label text-light" %>
            <div class="col-10">
              <%= form.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
            </div>
          </div>

            <div class="form-group row">
              <%= form.label :category, class: "col-2 col-form-label text-light" %>
                <div class="col-10">
                <%= form.collection_select(:category_ids, Category.all, :id, :name,
                {prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" }) %>
                </div>
            </div>

          <div class="form-group row justify-content-center">
              <%= form.submit class: "btn btn-outline-light col-2 mt-2 btn-lg" %>
          </div>
        <% end %>
      </div>
      <div class="mb-3 text-center">
        <%= link_to '[ Cancel and return to article listings ]', articles_path, class: "text-info text-center" %>
     </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form'%>

app/views/articles/index.html.erb
  <h1 class="text-center mt-4">Listing all articles</h1>
  
    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>

      <%= render 'article' %>

    <div class="flickr_pagination mb-4">
        <%= will_paginate @articles, :container => false %>
    </div>

app/views/articles/new.html.erb
    <h1 class="text-center mt-4">Create new article</h1>
    <%= render 'form' %>

app/views/articles/show.html.erb
  <h2 class="text-center mt-4"> <%= @article.title %> </h2>

  <div class="container">

    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header fst-italic">
            by <%= link_to @article.user.username, user_path(@article.user)%>
            <%= link_to gravatar_for(@article.user), user_path(@article.user)%>
            <% if @article.categories.any?%>
              <div class="mt-2"><%= render @article.categories %></div>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-start"><%= simple_format(@article.description) %></div>
              <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
                <%= link_to 'edit', edit_article_path(@article), class: "btn btn-outline-info"  %>
                <%= link_to 'delete', article_path(@article), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you REALLY sure?"} %> 
              <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at)%> ago, edited <%= time_ago_in_words(@article.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/articles/utility_index.html.erb
 <%# unclear on how exactly to route here... %>


<p id="notice"><%= notice %></p>

<h1 class="text-center mt-4">Utility Index</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>
<%= link_to 'Posts', posts_path %>