config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'search', to: 'pages#search'
  resources :articles
  # resources :posts 
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  # could restrict with a hash of only: [show, edit]
  #expose all REST-ful routes-- representational state transfer
  # basically a mapping of the HTTP verbs(get, post, put/patch, delete)
  # to CRUD actions in Rails App.
  #HTTP verbs front end requests -- CRUD actions backend responses.
  #frontend could be anything just as long as the HTTP verbs are being
  #translated into the appropriate/correct CRUD action.

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories 
    has_many :articles, through: :article_categories
    validates :name, presence: true, length: { minimum: 3, maximum: 25}
    validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def index 
          @categories = Category.paginate(page: params[:page], per_page: 5)
    end 


    def new 
        @category = Category.new
    end 

    def create 
        @category = Category.create(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else  
            render 'new'
        end 
    end 

    def edit 
        @category = Category.find(params[:id])
    end 

    def update 
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name updated successfully"
            redirect_to @category 
        else  
            render 'edit'
        end 
    end 

    def show 
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end 

    private 

    def category_params 
        params.require(:category).permit(:name)
    end 

    def require_admin 
       if !(logged_in? && current_user.admin)
        flash[:alert] = "Only admins can perform that action"
        redirect_to categories_path
       end 
    end 

end 

app/views/categories/_categories.html.erb
  <div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"> <%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="class-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Create ago <%= time_ago_in_words(category.created_at)%>, edited <%= time_ago_in_words(category.updated_at)%> ago</small>
          </div>
        </div>
      </div>
    </div>
  <%end%>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge bg-info text-light ms-1" %>

app/views/categories/_form.html.erb
  
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
        <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |form| %>
          <div class="form-group row">
            <%= form.label :name, "Category name", class: "col-2 col-form-label mb-2 text-light" %>
            <div class="col-10">
              <%= form.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
            </div>
          </div>
          <div class="form-group row justify-content-center">
              <%= form.submit class: "btn btn-outline-light" %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/categories/edit.html.erb
    <h1 class="text-center mt-4">Edit Category</h1>
    <%= render 'form' %>

    <div class="mb-3 text-center">
        <%= link_to '[ Cancel and return to category listing ]', category_path(@category), class: "text-info text-center" %>
    </div>

app/views/categories/index.html.erb
  <h1 class="text-center mt-4">Categories</h1>
  
    <div class="flickr_pagination">
        <%= will_paginate @categories, :container => false %>
    </div>

      <%= render 'categories' %>

    <div class="flickr_pagination mb-4">
        <%= will_paginate @categories, :container => false %>
    </div>

    <div class="mb-3 text-center">
        <%= link_to '[ Cancel and return to categories listings ]', categories_path, class: "text-info text-center" %>
    </div>

app/views/categories/new.html.erb
    <h1 class="text-center mt-4">New Category</h1>
    <%= render 'form' %>
    <div class="mb-3 text-center">
            <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-info text-center" %>
    </div>

app/views/categories/show.html.erb
    <h1 class="text-center mt-4"> Category: <%= @category.name %></h1>
        <% if logged_in? && current_user.admin %> 
            <div class="text-center mt-4">
                <%= link_to 'Edit Category name', edit_category_path(@category), class: "btn btn-outline-info" %>
            </div>
        <% end %>
    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>

      <%= render 'articles/article' %>

    <div class="flickr_pagination mb-4">
        <%= will_paginate @articles, :container => false %>
    </div>