config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'search', to: 'pages#search'
  resources :articles
  # resources :posts 
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  # could restrict with a hash of only: [show, edit]
  #expose all REST-ful routes-- representational state transfer
  # basically a mapping of the HTTP verbs(get, post, put/patch, delete)
  # to CRUD actions in Rails App.
  #HTTP verbs front end requests -- CRUD actions backend responses.
  #frontend could be anything just as long as the HTTP verbs are being
  #translated into the appropriate/correct CRUD action.

end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; <%= link_to "Aaron Whitmer", "http://127.0.0.1:4567/", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.erb
    
    
    <div class="container">
        <% flash.each do |name, msg| %>
            <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show" role="alert">
                <%= msg %> 
                <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        <% end %>
    </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-black">
  <div class="container-fluid">
    <%= link_to "WORDS", root_path, class: "navbar-brand", id: "logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link active" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Articles
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if logged_in? %>
              <%= link_to "New", new_article_path, class: "nav-link active"%>
            <% end %>
              <%= link_to "Articles", articles_path, class: "nav-link active"%>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
        
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in? && current_user.admin? %>
                <%= link_to "New", new_category_path, class: "nav-link active"%>
              <% end %>
                <%= link_to "Categories", categories_path, class: "nav-link active"%>
        
        </li>
          <% if logged_in? %>
             <li class="nav-item">
                <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "(admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View your profile", user_path(current_user), class: "nav-link active"%>
              <%= link_to "Edit your profile", edit_user_path(current_user), class: "nav-link active"%>
              <%= link_to "Delete profile", user_path(current_user), class: "nav-link active text-danger", method: :delete, data: { confirm: "Are you sure?"} %>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
        
        </li>
              </li>
              <li class="nav-item">
                <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete%>
              </li>
          <% else %>
              <li class="nav-item">
                <%= link_to 'Log in', login_path, class: "nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to 'Sign up', signup_path, class: "nav-link" %>
              </li>
          <% end %>
      </ul>
      <form action="/search" method="get" class="d-flex">
        <input class="form-control me-2" type="search" name="search_word" placeholder="keyword(s)" aria-label="Search">
        <button class="btn btn-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div id="page-content">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>